name: perisai
description: Aplikasi parental control berbasis AI untuk mendeteksi konten judi online
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.0

  # State Management
  flutter_riverpod: ^2.5.0

  # Navigation
  go_router: ^14.0.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Storage lokal
  shared_preferences: ^2.2.0

  # Permission
  permission_handler: ^11.3.0

  # Image
  cached_network_image: ^3.3.0

  # Format tanggal
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true